namespace NWN.FinalFantasy.Core.NWScript.Enumerations
{
    public enum ClassType
    {
        Barbarian = 0,
        Bard = 1,
        Cleric = 2,
        Druid = 3,
        Fighter = 4,
        Monk = 5,
        Paladin = 6,
        Ranger = 7,
        Rogue = 8,
        Sorcerer = 9,
        Wizard = 10,
        Aberration = 11,
        Animal = 12,
        Construct = 13,
        Humanoid = 14,
        Monstrous = 15,
        Elemental = 16,
        Fey = 17,
        Dragon = 18,
        Undead = 19,
        Commoner = 20,
        Beast = 21,
        Giant = 22,
        Magical_Beast = 23,
        Outsider = 24,
        Shapechanger = 25,
        Vermin = 26,
        Shadowdancer = 27,
        Harper = 28,
        Arcane_Archer = 29,
        Assassin = 30,
        Blackguard = 31,
        Divinechampion = 32,
        Divine_Champion = 32,
        Weapon_Master = 33,
        Palemaster = 34,
        Pale_Master = 34,
        Shifter = 35,
        DwarvenDefender = 36,
        Dwarven_Defender = 36,
        Dragondisciple = 37,
        Dragon_Disciple = 37,
        Ooze = 38,
        Eye_Of_Gruumsh = 39,
        Shou_Disciple = 40,
        Purple_Dragon_Knight = 41,
        Invalid = 255,

    }
}
