namespace NWN.FinalFantasy.Core.NWScript.Enum.VisualEffect
{
    public enum Common
    {
        SpecialBlueRed = 100,
        SpecialPinkOrange,
        SpecialRedWhite,
        SpecialRedOrange,
        SpecialWhiteBlue,
        SpecialWhiteOrange,
        BloodRegWimp,
        BloodLrgWimp,
        BloodCrtWimp,
        BloodRegRed,
        BloodRegGreen,
        BloodRegYellow,
        BloodLrgRed,
        BloodLrgGreen,
        BloodLrgYellow,
        BloodCrtRed,
        BloodCrtGreen,
        BloodCrtYellow,
        SparksParry = 118,
        UnloadModel = 120,
        ChunkRedSmall,
        ChunkRedMedium,
        ChunkGreenSmall,
        ChunkGreenMedium,
        ChunkYellowSmall,
        ChunkYellowMedium,
        ChunkRedLarge = 235,
        ChunkBoneMedium,
        BloodSparkSmall,
        BloodSparkMedium,
        BloodSparkLarge,
        HitFire = 280,
        HitFrost,
        HitElectrical,
        HitAcid,
        HitSonic,
        HitNegative = 288,
        HitDivine,
        ChunkStoneSmall = 353,
        ChunkStoneMedium = 354,
        ChunkRedBallista = 504
    }
}