namespace NWN.FinalFantasy.Core.NWScript.Enum.Item
{
    public enum EquipmentSlot
    {
        Head,
        Chest,
        Boots,
        Arms,
        RightHand,
        LeftHand,
        Cloak,
        LeftRing,
        RightRing,
        Neck,
        Belt,
        Arrows,
        Bullets,
        Bolts,
        CreatureWeaponLeft,
        CreatureWeaponRight,
        CreatureWeaponBite,
        CreatureArmour
    }

    public enum BaseItem
    {
        ShortSword = 0,
        Longsword = 1,
        BattleAxe = 2,
        BastardSword = 3,
        LightFlail = 4,
        WarHammer = 5,
        HeavyCrossbow = 6,
        LightCrossbow = 7,
        Longbow = 8,
        LightMace = 9,
        Halberd = 10,
        ShortBow = 11,
        TwoBladedSword = 12,
        GreatSword = 13,
        SmallShield = 14,
        Torch = 15,
        Armor = 16,
        Helmet = 17,
        GreatAxe = 18,
        Amulet = 19,
        Arrow = 20,
        Belt = 21,
        Dagger = 22,
        MiscSmall = 24,
        Bolt = 25,
        Boots = 26,
        Bullet = 27,
        Club = 28,
        MiscMedium = 29,
        Dart = 31,
        DireMace = 32,
        DoubleAxe = 33,
        MiscLarge = 34,
        HeavyFlail = 35,
        Gloves = 36,
        LightHammer = 37,
        HandAxe = 38,
        HealersKit = 39,
        Kama = 40,
        Katana = 41,
        Kukri = 42,
        MiscTall = 43,
        MagicRod = 44,
        MagicStaff = 45,
        MagicWand = 46,
        MorningStar = 47,
        Potions = 49,
        QuarterStaff = 50,
        Rapier = 51,
        Ring = 52,
        Scimitar = 53,
        Scroll = 54,
        Scythe = 55,
        LargeShield = 56,
        TowerShield = 57,
        ShortSpear = 58,
        Shuriken = 59,
        Sickle = 60,
        Sling = 61,
        ThievesTools = 62,
        ThrowingAxe = 63,
        TrapKit = 64,
        Key = 65,
        LargeBox = 66,
        MiscWide = 68,
        CreatureSlashWeapon = 69,
        CreaturePierceWeapon = 70,
        CreatureBludgeWeapon = 71,
        CreatureSlashPierceWeapon = 72,
        CreatureItem = 73,
        Book = 74,
        SpellScroll = 75,
        Gold = 76,
        Gem = 77,
        Bracer = 78,
        MiscThin = 79,
        Cloak = 80,
        Grenade = 81,
        Encampment = 82,
        Lance = 92,
        Trumpet = 92,
        MoonOnAStick = 92,
        Trident = 95,
        BlankPotion = 101,
        BlankScroll = 102,
        BlankWand = 103,
        EnchantedPotion = 104,
        EnchantedScroll = 105,
        EnchantedWand = 106,
        DwarvenWarAxe = 108,
        CraftMaterialMedium = 109,
        CraftMaterialSmall = 110,
        Whip = 111,
        CraftBase = 112,
        Invalid = 255
    }

    public enum ItemAppearance
    {
        Color_Leather1 = -9,
        Color_Leather2 = -8,
        Color_Cloth1 = -7,
        Color_Cloth2 = -6,
        Color_Metal1 = -5,
        Color_Metal2 = -4,
        Model_Part1 = -3,
        Model_Part2 = -2,
        Model_Part3 = -1,
        ArmorModel_RightFoot = 0,
        ArmorModel_LightFoot = 1,
        ArmorModel_RightShin = 2,
        ArmorModel_LightShin = 3,
        ArmorModel_LightThigh = 4,
        ArmorModel_RightThigh = 5,
        ArmorModel_Pelvis = 6,
        ArmorModel_Torso = 7,
        ArmorModel_Belt = 8,
        ArmorModel_Neck = 9,
        ArmorModel_RightForearm = 10,
        ArmorModel_LightForearm = 11,
        ArmorModel_RightBicep = 12,
        ArmorModel_LightBicep = 13,
        ArmorModel_RightShoulder = 14,
        ArmorModel_LightShoulder = 15,
        ArmorModel_RightHand = 16,
        ArmorModel_LightHand = 17,
        ArmorModel_Robe = 18
    }

    public enum ItemAppearanceType
    {
        SimpleModel,
        WeaponColor,
        WeaponModel,
        ArmorModel,
        ArmorColor
    }

    public enum ItemPropertyType
    {
        AbilityBonus = 0,
        ACBonus = 1,
        ACBonusVsAlignmentGroup = 2,
        ACBonusVsDamageType = 3,
        ACBonusVsRacialGroup = 4,
        ACBonusVsSpecificAlignment = 5,
        EnhancementBonus = 6,
        EnhancementBonusVsAlignmentGroup = 7,
        EnhancementBonusVsRacialGroup = 8,
        EnhancementBonusVsSpecificAlignement = 9,
        DecreasedEnhancementModifier = 10,
        BaseItemWeightReduction = 11,
        BonusFeat = 12,
        BonusSpellSlotOfLevelN = 13,
        CastSpell = 15,
        DamageBonus = 16,
        DamageBonusVsAlignmentGroup = 17,
        DamageBonusVsRacialGroup = 18,
        DamageBonusVsSpecificAlignment = 19,
        ImmunityDamageType = 20,
        DecreasedDamage = 21,
        DamageReduction = 22,
        DamageResistance = 23,
        DamageVulnerability = 24,
        Darkvision = 26,
        DecreasedAbilityScore = 27,
        DecreasedAC = 28,
        DecreasedSkillModifier = 29,
        EnhancedContainerReducedWeight = 32,
        ExtraMeleeDamageType = 33,
        ExtraRangedDamageType = 34,
        Haste = 35,
        HolyAvenger = 36,
        ImmunityMiscellaneous = 37,
        ImprovedEvasion = 38,
        SpellResistance = 39,
        SavingThrowBonus = 40,
        SavingThrowBonusSpecific = 41,
        Keen = 43,
        Light = 44,
        Mighty = 45,
        MindBlank = 46,
        NoDamage = 47,
        OnHitProperties = 48,
        DecreasedSavingThrows = 49,
        DecreasedSavingThrowsSpecific = 50,
        Regeneration = 51,
        SkillBonus = 52,
        ImmunitySpecificSpell = 53,
        ImmunitySpellSchool = 54,
        ThievesTools = 55,
        AttackBonus = 56,
        AttackBonusVsAlignmentGroup = 57,
        AttackBonusVsRacialGroup = 58,
        AttackBonusVsSpecificAlignment = 59,
        DecreasedAttackModifier = 60,
        UnlimitedAmmunition = 61,
        UseLimitationAlignmentGroup = 62,
        UseLimitationClass = 63,
        UseLimitationRacialType = 64,
        UseLimitationSpecificAlignment = 65,
        UseLimitationTileset = 66,
        RegenerationVampiric = 67,
        Trap = 70,
        TrueSeeing = 71,
        OnMonsterHit = 72,
        TurnResistance = 73,
        MassiveCriticals = 74,
        FreedomOfMovement = 75,
        Poison = 76, // no longer working, poison is now a onHit  subtype
        MonsterDamage = 77,
        ImmunitySpellsByLevel = 78,
        SpecialWalk = 79,
        HealersKit = 80,
        WeightIncrease = 81,
        Onhitcastspell = 82,
        Visualeffect = 83,
        ArcaneSpellFailure = 84,
        Material = 85,
        Quality = 86,
        Additional = 87
    }
}